version: "3.8"

services:
  postgres-order:
    image: postgres:15
    container_name: postgres-order
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata_order:/var/lib/postgresql/data
    networks:
      - app_network

  order-service:
    image: quay.io/novelnest/order-service:latest
    # build: .
    container_name: order-service
    depends_on:
      - postgres-order
    ports:
      - "5010:5010"
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      INVENTORY_SERVICE_URL: ${INVENTORY_SERVICE_URL}
    volumes:
      - ./prisma:/app/prisma
    networks:
      - app_network
